[target.x86_64-unknown-linux-gnu]
rustflags = [ "-C", "link-args=-rdynamic" ]

[target.i686-unknown-linux-gnu]
rustflags = [ "-C", "link-args=-rdynamic" ]

[target.aarch64-unknown-linux-musl]
rustflags = [ "-C", "link-args=-rdynamic" ]

[target.arm-unknown-linux-musleabihf]
rustflags = [ "-C", "link-args=-rdynamic" ]

[target.armv7-unknown-linux-musleabihf]
rustflags = [ "-C", "link-args=-rdynamic" ]

[target.i686-unknown-linux-musl]
rustflags = [ "-C", "link-args=-rdynamic" ]

[target.x86_64-unknown-linux-musl]
rustflags = [ "-C", "link-args=-rdynamic" ]
