[workspace]
resolver = "2"
members = [
    "crates/build_utils/find_julia",
    "crates/build_utils/jlrs_compat",
    "crates/ffi/jl_sys",
    "crates/ffi/jlrs_sys",
    "crates/jlrs",
    "crates/jlrs_macros",
]
exclude = ["examples","tests/julia_module_test", "benches"]
