
[workspace]
# members = ["benches", "examples", "jl_sys", "jlrs", "jlrs_macros", "julia_module_test"]
members = ["examples", "jl_sys", "jlrs", "jlrs_macros"]
exclude = ["julia_module_test", "benches"]
