name: Module tests
description: Set up Julia and Rust and run the module test suite

inputs:
  julia-version:
    description: Julia version to use
    required: false

  rust-toolchain:
    description: Rust toolchain to use
    required: true

  jlrs-core-revision:
    description: "JlrsCore revision to use"
    required: true

runs:
  using: composite
  steps:
    - name: Setup Julia
      id: setup-julia
      uses: julia-actions/setup-julia@v3
      with:
        version: ${{ inputs.julia-version }}

    - uses: julia-actions/cache@v3

    - name: Setup Rust
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: ${{ inputs.rust-toolchain }}
      
    - name: Build library
      shell: bash
      run: |
        cd tests/julia_module_test
        cargo build --features "jlrs/jl-docs"

    - uses: julia-actions/cache@v3

    - name: Install Julia dependencies
      shell: bash
      run: |
        julia -e 'import Pkg; Pkg.add(url="https://github.com/Taaitaaiger/JlrsCore.jl", rev="${{ inputs.jlrs-core-revision }}"); Pkg.add("StaticArrays"); Pkg.add("Documenter")'

    - name: Run script tests
      shell: bash
      env:
        JLRS_JULIA_DIR: ${{ steps.setup-julia.outputs.julia-bindir }}/..
        LD_LIBRARY_PATH: ${{ steps.setup-julia.outputs.julia-bindir }}/../lib
        DYLD_LIBRARY_PATH: ${{ steps.setup-julia.outputs.julia-bindir }}/../lib
        JULIA_MODULE_TEST_LIB_DIR: ${{ github.workspace }}/tests/julia_module_test/target/debug
      run: |
        cd tests/script
        julia JuliaModuleTest.jl

    - name: Run package tests
      shell: bash
      env:
        JLRS_JULIA_DIR: ${{ steps.setup-julia.outputs.julia-bindir }}/..
        LD_LIBRARY_PATH: ${{ steps.setup-julia.outputs.julia-bindir }}/../lib
        DYLD_LIBRARY_PATH: ${{ steps.setup-julia.outputs.julia-bindir }}/../lib
        JULIA_MODULE_TEST_LIB_DIR: ${{ github.workspace }}/tests/julia_module_test/target/debug
      run: |
        cd tests/JuliaModuleTest
        julia --project=. -e '
          using Pkg
          Pkg.instantiate()'
        julia --project=. test/runtests.jl

    - name: Instantiate docs
      shell: bash
      env:
        JLRS_JULIA_DIR: ${{ steps.setup-julia.outputs.julia-bindir }}/..
        LD_LIBRARY_PATH: ${{ steps.setup-julia.outputs.julia-bindir }}/../lib
        DYLD_LIBRARY_PATH: ${{ steps.setup-julia.outputs.julia-bindir }}/../lib
        JULIA_MODULE_TEST_LIB_DIR: ${{ github.workspace }}/tests/julia_module_test/target/debug
      run: |
        cd tests/JuliaModuleTest
        julia --project=docs -e '
          using Pkg
          Pkg.develop(PackageSpec(path=pwd()))
          Pkg.instantiate()'

    - name: Doctests
      shell: bash
      env:
        JLRS_JULIA_DIR: ${{ steps.setup-julia.outputs.julia-bindir }}/..
        LD_LIBRARY_PATH: ${{ steps.setup-julia.outputs.julia-bindir }}/../lib
        DYLD_LIBRARY_PATH: ${{ steps.setup-julia.outputs.julia-bindir }}/../lib
        JULIA_MODULE_TEST_LIB_DIR: ${{ github.workspace }}/tests/julia_module_test/target/debug
      run: |
        cd tests/JuliaModuleTest
        julia --project=docs -e '
          using Documenter: doctest
          using JuliaModuleTest
          doctest(JuliaModuleTest)'

    - name: Docs
      shell: bash
      env:
        JLRS_JULIA_DIR: ${{ steps.setup-julia.outputs.julia-bindir }}/..
        LD_LIBRARY_PATH: ${{ steps.setup-julia.outputs.julia-bindir }}/../lib
        DYLD_LIBRARY_PATH: ${{ steps.setup-julia.outputs.julia-bindir }}/../lib
        JULIA_MODULE_TEST_LIB_DIR: ${{ github.workspace }}/tests/julia_module_test/target/debug
        JULIA_PKG_SERVER: ""
      run: |
        cd tests/JuliaModuleTest
        julia --project=docs docs/make.jl
      
    - name: Build library with static-cache
      shell: bash
      run: |
        cd tests/julia_module_test
        cargo build --features "jlrs/jl-docs,jlrs/static-cache""

    - name: Run script tests with static-cache
      shell: bash
      env:
        JLRS_JULIA_DIR: ${{ steps.setup-julia.outputs.julia-bindir }}/..
        LD_LIBRARY_PATH: ${{ steps.setup-julia.outputs.julia-bindir }}/../lib
        DYLD_LIBRARY_PATH: ${{ steps.setup-julia.outputs.julia-bindir }}/../lib
        JULIA_MODULE_TEST_LIB_DIR: ${{ github.workspace }}/tests/julia_module_test/target/debug
      run: |
        cd tests/script
        julia JuliaModuleTest.jl

    - name: Run package tests with static-cache
      shell: bash
      env:
        JLRS_JULIA_DIR: ${{ steps.setup-julia.outputs.julia-bindir }}/..
        LD_LIBRARY_PATH: ${{ steps.setup-julia.outputs.julia-bindir }}/../lib
        DYLD_LIBRARY_PATH: ${{ steps.setup-julia.outputs.julia-bindir }}/../lib
        JULIA_MODULE_TEST_LIB_DIR: ${{ github.workspace }}/tests/julia_module_test/target/debug
      run: |
        cd tests/JuliaModuleTest
        julia --project=. -e '
          using Pkg
          Pkg.instantiate()'
        julia --project=. test/runtests.jl
