name: Embedding (LTS)

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

concurrency:
  # Skip intermediate builds: always.
  # Cancel intermediate builds: only if it is a pull request build.
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}

env:
  jlrs-core-revision: "0f1b7cba4eeedae260cb48374716f3cd551fc8c0"
  julia-version: "1.10"

jobs:
  test-linux-macos:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        rust: [stable]

    runs-on: ${{ matrix.os }}
    permissions: # needed to allow julia-actions/cache to proactively delete old caches that it has created
      actions: write
      contents: read

    steps:
      - uses: actions/checkout@v6

      - name: Embedding tests
        uses: ./.github/actions/embedding-tests
        with:
          rust-toolchain: ${{ matrix.rust }}
          jlrs-core-revision: ${{ env.jlrs-core-revision }}
          julia-version: ${{ env.julia-version }}

  test-windows:
    strategy:
      matrix:
        rust:
          [
            stable-x86_64-pc-windows-gnu,
            stable-x86_64-pc-windows-msvc,
          ]

    runs-on: windows-2022
    permissions: # needed to allow julia-actions/cache to proactively delete old caches that it has created
      actions: write
      contents: read

    steps:
      - uses: actions/checkout@v6

      - name: Embedding tests
        uses: ./.github/actions/embedding-tests
        with:
          rust-toolchain: ${{ matrix.rust }}
          jlrs-core-revision: ${{ env.jlrs-core-revision }}
          julia-version: ${{ env.julia-version }}
