name: Module (LTS)

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

concurrency:
  # Skip intermediate builds: always.
  # Cancel intermediate builds: only if it is a pull request build.
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}

env:
  jlrs-core-revision: "0f1b7cba4eeedae260cb48374716f3cd551fc8c0"
  julia-version: "1.13"

jobs:
  tests:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        rust: [stable]
        allow-fail: [false]

    continue-on-error: ${{ matrix.allow-fail }}
    runs-on: ${{ matrix.os }}
    permissions: # needed to allow julia-actions/cache to proactively delete old caches that it has created
      actions: write
      contents: read

    steps:
      - uses: actions/checkout@v6

      - name: Module tests
        uses: ./.github/actions/module-tests
        with:
          rust-toolchain: ${{ matrix.rust }}
          jlrs-core-revision: ${{ env.jlrs-core-revision }}
          julia-version: ${{ env.julia-version }}


    #   - name: Setup Julia environment
    #     uses: julia-actions/setup-julia@v3
    #     with:
    #       version: '1.12'

    #   - name: Setup Rust
    #     uses: dtolnay/rust-toolchain@master
    #     with:
    #       toolchain: stable

    #   - name: Build library
    #     run: |
    #       cd tests/julia_module_test
    #       cargo build --features "jlrs/jl-docs"

    #   - uses: julia-actions/cache@v3

    #   - name: Script tests
    #     run: |
    #       cd tests/script
    #       julia -e "import Pkg; Pkg.add(url=\"https://github.com/Taaitaaiger/JlrsCore.jl\", rev=\"0f1b7cba4eeedae260cb48374716f3cd551fc8c0\"); Pkg.add(\"StaticArrays\")"
    #       export JULIA_MODULE_TEST_LIB_DIR="${GITHUB_WORKSPACE}/tests/julia_module_test/target/debug"
    #       julia JuliaModuleTest.jl

    #   - name: Package tests
    #     run: |
    #       cd tests/JuliaModuleTest
    #       export JULIA_MODULE_TEST_LIB_DIR="${GITHUB_WORKSPACE}/tests/julia_module_test/target/debug"
    #       julia --project=. -e '
    #         using Pkg
    #         Pkg.instantiate()'
    #       julia --project=. test/runtests.jl

    #   - name: Instantiate docs
    #     run: |
    #       cd tests/JuliaModuleTest
    #       export JULIA_MODULE_TEST_LIB_DIR="${GITHUB_WORKSPACE}/tests/julia_module_test/target/debug"
    #       julia --project=docs -e '
    #         using Pkg
    #         Pkg.develop(PackageSpec(path=pwd()))
    #         Pkg.instantiate()'

    #   - name: Install Documenter
    #     run: |
    #       julia -e "import Pkg; Pkg.add(\"Documenter\")"

    #   - name: Doctests
    #     run: |
    #       cd tests/JuliaModuleTest
    #       export JULIA_MODULE_TEST_LIB_DIR="${GITHUB_WORKSPACE}/tests/julia_module_test/target/debug"
    #       julia --project=docs -e '
    #         using Documenter: doctest
    #         using JuliaModuleTest
    #         doctest(JuliaModuleTest)'

    #   - name: Docs
    #     run: |
    #       cd tests/JuliaModuleTest
    #       export JULIA_MODULE_TEST_LIB_DIR="${GITHUB_WORKSPACE}/tests/julia_module_test/target/debug"
    #       julia --project=docs docs/make.jl
    #     env:
    #       JULIA_PKG_SERVER: ""

    #   - name: Build library with static-cache
    #     run: |
    #       cd tests/julia_module_test
    #       cargo build --features "jlrs/jl-docs,jlrs/static-cache"

    #   - name: Script tests with static-cache
    #     run: |
    #       cd tests/script
    #       export JULIA_MODULE_TEST_LIB_DIR="${GITHUB_WORKSPACE}/tests/julia_module_test/target/debug"
    #       julia JuliaModuleTest.jl

    #   - name: Package tests with static-cache
    #     run: |
    #       cd tests/JuliaModuleTest
    #       export JULIA_MODULE_TEST_LIB_DIR="${GITHUB_WORKSPACE}/tests/julia_module_test/target/debug"
    #       julia --project=. -e '
    #         using Pkg
    #         Pkg.instantiate()'
    #       julia --project=. test/runtests.jl